AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'

# Don't complain about long block lengths.
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 150

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '(\A|\s)#' # Don't get upset at comments longer than the line length.
    - 'authorize %' # Exclude Pundit authorization calls
    - 'belongs_to :'
    - 'has_many :'
    - 'has_and_belongs_to_many :'
    - 'has_one :'

Metrics/ModuleLength:
  CountComments: false # count full line comments?
  Max: 150

# Don't complain about top-level class documentation comments.
Style/Documentation:
  Enabled: false

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

# Don't require the magic comment for Ruby 2.3
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
